### ISSUE TITLE
Getting started - text formatting 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#147]
Headlines are not formatted in either English or French version.  Indents need to be removed from French version. 

![image](https://user-images.githubusercontent.com/59370537/76306371-1e8a7780-629d-11ea-8c8b-b179019918b6.png)

![image](https://user-images.githubusercontent.com/59370537/76306387-29dda300-629d-11ea-85a9-f158bac79819.png)

**Comment by AJBouzidi** [comment]
This is has been fixed please reopen it if the functionality not working as expected.

**Comment by mullhol** [comment]
Headlines are still not formatted.  Headlines are as follows:

Why we are conducting this study 

Notifications

Authorization and confidentiality 

Record linkages 

Time required to complete this questionnaire 

To navigate the questionnaire 

Session timeout 

Definitions and explanations 


Pourquoi nous menons cette étude 

Notifications

Autorisation et confidentialité 

Couplages d’enregistrements 

Temps requis pour remplir ce questionnaire 

Pour parcourir le questionnaire 

Délai d’inactivité d’une session 

Définitions et explications

Refer to UX file for look and feel...
![image](https://user-images.githubusercontent.com/59370537/81563002-b2db8e00-9363-11ea-877c-9ed1726b26ca.png)

**Comment by mullhol** [comment]
Model based on UX style guide, as outlined with Contact Us page as an example

![image](https://user-images.githubusercontent.com/59370537/81950851-782b5d00-95d2-11ea-8f7d-eb2e8d9e8c0e.png)

**Comment by AJBouzidi** [comment]
@mullhol basically the changes will be bold style for the Headlines and no space between the headline and the following paragraph?

**Comment by mullhol** [comment]
@AJBouzidi Yes, and revised font colour for the headings.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, please reopen this issue if the functionality not working as expected.
